conta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from .settings import STATICFILES_DIRS

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('vencimientos/', include('vencimientos.urls')),
    
    # Serve the favicon
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': STATICFILES_DIRS[0],
        }
    ),
]

main/urls.py
from django.urls import path

from .views import *

# Sólo para deploy .........
from django.conf import settings
from django.conf.urls.static import static
#  .........

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('clientes/', EmpresaList.as_view(), name='empresas_list'),
    path('clientes/create', EmpresaCreate.as_view(), name = 'empresa_create'),
    path('clientes/<str:pk>/update', EmpresaUpdate.as_view(), name = 'empresa_update'),
    path('clientes/<str:pk>/delete', EmpresaDelete.as_view(), name = 'empresa_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vencimientos/urls.py
from django.urls import path

from .views import *

app_name = 'vencimientos'

urlpatterns = [
    #Generador Vencimientos
    path('generate', VenceGenerate.as_view(), name = 'generate'),
    #Vencimientos por impuesto
    path('vi/', VenceImpList.as_view(), name='vi_list'),
    path('vi/create', VenceImpCreate.as_view(), name = 'vi_create'),
    path('vi/<str:pk>/update', VenceImpUpdate.as_view(), name = 'vi_update'),
    path('vi/<str:pk>/delete', VenceImpDelete.as_view(), name = 'vi_delete'),
    
    #Vencimientos por cliente
    path('ve/', VenceEmpList.as_view(), name='ve_list'),
    path('ve/create', VenceEmpCreate.as_view(), name = 've_create'),
    path('ve/<str:pk>/update', VenceEmpUpdate.as_view(), name = 've_update'),
    path('ve/<str:pk>/delete', VenceEmpDelete.as_view(), name = 've_delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/fontawesome-free-6.0.0-web/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.20/css/adminlte.min.css' %}">
    <!-- Block head -->
    <!--  SCRIPTS -->
    <!-- jQuery -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/bootstrap-4.6.1-dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.20/js/adminlte.min.js' %}"></script>
    <!-- Para Agregar librerias -->
    {% block head%}{% endblock %}
</head>
{% block body %} {% endblock %}

</html>

templates/body.html
{% extends 'base.html' %} {% block body %}

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>tu<b>Conta</b> 1.0</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %} {% endblock %}
</body>
{% endblock %}

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer text-center">
    <strong>Copyright &copy; 2021-2022 <a href="https://ceciliaprados.com.ar">ArtimeZoft</a>.</strong><br> Todos los derechos reservados.
</footer>

templates/form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="email">{{ field.label }}:</label>
                        {{ field|add_class:'form-control' }}
                    </div>
                {% endfor %}
                {% block agregado %}

                {% endblock %}
                
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>

    </script>
{% endblock %}

templates/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">
                        Último Acceso: 12 de Abril de 2020
                    </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/list.html
{% extends 'body.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'lib/datatables-1.11.5/css/dataTables.bootstrap5.min.css' %}" />
<link rel="stylesheet" href="{% static 'lib/datatables-1.11.5/responsive-2.2.9/css/responsive.bootstrap5.min.css' %}" />

<script src="{% static 'lib/datatables-1.11.5/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib/datatables-1.11.5/js/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.11.5/responsive-2.2.9/js/dataTables.responsive.js' %}"></script>
<script src="{% static 'lib/datatables-1.11.5/responsive-2.2.9/js/responsive.bootstrap5.min.js' %}"></script>


{% block head_list %} {% endblock %} {% endblock %} {% block content %} {% block agregado %} {% endblock %}
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fas fa-search"></i> {{ title }}
        </h3>
    </div>
    <div class="card-body">
        <table class="table" id="tabla_d">
            <thead>
                {% block columns %} {% endblock %}
            </thead>
            <tbody>
                {% block rows %} {% endblock %}
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
            <i class="fas fa-plus"></i> Nuevo registro
        </a>
        <a href="{{ list_url }}" class="btn btn-success btn-flat">
            <i class="fas fa-sync"></i> Actualizar
        </a>
    </div>
</div>
{% endblock %} {% block javascript %}
<script type="application/javascript">
    $(function() {
        $('#tabla_d').DataTable({
            responsive: true,
            autoWidth: false
        });

    });
</script>
{% endblock %}

templates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="{% url 'main' %}" class="brand-link">
        <img src="{% static 'img/logo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">tu<b>Conta</b></span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="{% url 'main' %}" class="d-block">Estudio Contable</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{% url 'empresas_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Clientes
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-folder"></i>
                        <p>
                            Archivos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-file-invoice"></i>
                        <p>
                            Facturación
                        </p>
                    </a>
                </li>
                <li class="nav-header">Vencimientos</li>
                <li class="nav-item">
                    <a href="{% url 'vencimientos:generate' %}" class="nav-link">
                        <i class="nav-icon fas fa-magic"></i>
                        <p>
                            Generación
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'vencimientos:vi_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-sticky-note"></i>
                        <p>
                            Por Impuesto
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'vencimientos:ve_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-calendar-check"></i>
                        <p>
                            Por Cliente
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>