conta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from .settings import STATICFILES_DIRS

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('vencimientos/', include('vencimientos.urls')),
    
    # Serve the favicon
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': STATICFILES_DIRS[0],
        }
    ),
]

main/urls.py
from django.urls import path

from .views import *

# Sólo para deploy .........
from django.conf import settings
from django.conf.urls.static import static
#  .........

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('clientes/', EmpresaList.as_view(), name='empresas_list'),
    path('clientes/create', EmpresaCreate.as_view(), name = 'empresa_create'),
    path('clientes/<str:pk>/update', EmpresaUpdate.as_view(), name = 'empresa_update'),
    path('clientes/<str:pk>/delete', EmpresaDelete.as_view(), name = 'empresa_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vencimientos/urls.py
from django.urls import path

from .views import *

app_name = 'vencimientos'

urlpatterns = [
    #Generador Vencimientos
    path('generate', VenceGenerate.as_view(), name = 'generate'),
    #Vencimientos por impuesto
    path('vi/', VenceImpList.as_view(), name='vi_list'),
    path('vi/create', VenceImpCreate.as_view(), name = 'vi_create'),
    path('vi/<str:pk>/update', VenceImpUpdate.as_view(), name = 'vi_update'),
    path('vi/<str:pk>/delete', VenceImpDelete.as_view(), name = 'vi_delete'),
    
    #Vencimientos por cliente
    path('ve/', VenceEmpList.as_view(), name='ve_list'),
    path('ve/create', VenceEmpCreate.as_view(), name = 've_create'),
    path('ve/<str:pk>/update', VenceEmpUpdate.as_view(), name = 've_update'),
    path('ve/<str:pk>/delete', VenceEmpDelete.as_view(), name = 've_delete'),
]

vencimientos/models.py
from django.db import models

from main.models import Empresa, Impuesto

class ReglaVencimiento(models.Model):
    #Si todas son la misma fecha no genera un registro, por ejemplo Com e Ind día 15
    impuesto = models.ForeignKey(Impuesto, on_delete=models.CASCADE)
    cuit_d = models.IntegerField(default=0)
    cuit_h = models.IntegerField(default=9)
    dia = models.IntegerField() #Si no está es día inicio y luego suma a este

    def __str__(self):
        return f'{self.impuesto} - {self.cuit_d} a {self.cuit_h} - Día {self.dia}'
    
    class Meta:
        ordering = ['impuesto', 'dia']

class Venc_Imp(models.Model):
    periodo = models.DateField() #dia 1 del mes o del año
    impuesto = models.ForeignKey(Impuesto, on_delete=models.CASCADE)
    cuit_d = models.IntegerField(default=0)
    cuit_h = models.IntegerField(default=9)
    fecha = models.DateField()

    def __str__(self):
        return f'{self.periodo.strftime("%m/%Y")} - {self.impuesto} - {self.fecha.strftime("%d/%m/%Y")}'

class Venc_Cli (models.Model):
    periodo = models.DateField() #dia 1 del mes o del año
    impuesto = models.ForeignKey(Impuesto, on_delete=models.CASCADE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    fecha = models.DateField()

    def __str__(self):
        return f'{self.empresa} - {self.impuesto} - {self.periodo.strftime("%m/%Y")}'

vencimientos/views.py
from datetime import datetime, timedelta
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView, TemplateView

from .models import Venc_Imp, Venc_Cli

#Vencimientos por impuesto ------------------------------------
class VenceImpList(ListView):
    model = Venc_Imp

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Vencimientos por Impuesto'
        context['create_url'] = reverse_lazy('vencimientos:vi_create')
        context['list_url'] = reverse_lazy('vencimientos:vi_list')
        context['entity'] = 'Vencimientos por Impuesto'
        return context
    
class VenceImpCreate(CreateView):
    model = Venc_Imp
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy ('vencimientos:vi_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Agregar Vencimiento'
        context['list_url'] = reverse_lazy('vencimientos:vi_list')
        context['entity'] = 'Vencimientos por Impuesto'
        context['action'] = 'add'
        return context

#class VenceImpDetail(DetailView):
#    model = Venc_Imp
# Por el momento no es necesario

class VenceImpUpdate(UpdateView):
    model = Venc_Imp
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy ('vencimientos:vi_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Vencimiento'
        context['list_url'] = reverse_lazy('vencimientos:vi_list')
        context['entity'] = 'Vencimientos por Impuesto'
        context['action'] = 'edit'
        return context

class VenceImpDelete(DeleteView):
    model = Venc_Imp

    def get_success_url(self):
        return reverse_lazy ('vencimientos:vi_list')

#Vencimientos por cliente ------------------------------------
class VenceEmpList(ListView):
    model = Venc_Cli

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Vencimientos por Empresa'
        context['create_url'] = reverse_lazy('vencimientos:ve_create')
        context['list_url'] = reverse_lazy('vencimientos:ve_list')
        context['entity'] = 'Vencimientos por Empresa'
        return context
    
class VenceEmpCreate(CreateView):
    model = Venc_Cli
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy ('vencimientos:ve_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Agregar Vencimiento'
        context['list_url'] = reverse_lazy('vencimientos:ve_list')
        context['entity'] = 'Vencimientos por Empresa'
        context['action'] = 'add'
        return context

#class VenceEmpDetail(DetailView):
#    model = Venc_Cli
# Por el momento no es necesario

class VenceEmpUpdate(UpdateView):
    model = Venc_Cli
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy ('vencimientos:ve_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Vencimiento'
        context['list_url'] = reverse_lazy('vencimientos:ve_list')
        context['entity'] = 'Vencimientos por Empresa'
        context['action'] = 'edit'
        return context

class VenceEmpDelete(DeleteView):
    model = Venc_Cli

    def get_success_url(self):
        return reverse_lazy ('vencimientos:ve_list')

#Generate ------------------------------------
class VenceGenerate(TemplateView):
    template_name = 'vencimientos/venc_generate.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # start_month = datetime.today().replace(day=1)

        # if start_month.month == 12:
        #     end_month = start_month.replace(day=1)
        # else:
        #     end_month = start_month.replace(month=start_month.month+1) - timedelta(days=1)
         
        # context['desde'] = start_month
        # context['hasta'] = end_month
        return context


vencimientos/templates/vencimientos/venc_cli_confirm_delete.html
{% extends 'base.html' %} {% block body %}
<h1>Borrar Vencimiento</h1>

<p>¿Estás seguro de borrar el vencimiento <b>{{ venc_cli }}</b>?</p>

<form action="" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-secondary btn-flat">
      <i class="fas fa-eraser"></i> Si! borrar.
  </button>
    <a href="{% url 'vencimientos:ve_list' %}" class="btn btn-danger btn-flat">
        <i class="fas fa-times"></i> Cancelar
    </a>
</form>
{% endblock %}

vencimientos/templates/vencimientos/venc_cli_form.html
{% extends 'form.html' %}

vencimientos/templates/vencimientos/venc_cli_list.html
{% extends 'list.html' %} {% load static %} {% block columns %}
<tr>
    <th scope="col" style="width: 18%;">Período</th>
    <th scope="col" style="width: 25%;">Impuesto</th>
    <th scope="col" style="width: 27%;">Impuesto</th>
    <th scope="col" style="width: 10%;">Fecha</th>
    <th scope="col" style="width: 20%;">Opciones</th>
</tr>
{% endblock %} {% block rows %} {% for obj in object_list %}
<tr>
    <td>{{ obj.periodo|date:'F Y' }}</td>
    <td>{{ obj.impuesto }}</td>
    <td>{{ obj.empresa }}</td>
    <td>{{ obj.fecha|date:'d/m/Y' }}</td>
    <td class="text-center">
        <a href="{% url 'vencimientos:ve_update' obj.id %}" class="btn btn-warning btn-xs btn-flat">
            <i class="fas fa-edit"></i>
        </a>
        <a href="{% url 'vencimientos:ve_delete' obj.id %}" class="btn btn-danger btn-xs btn-flat">
            <i class="fas fa-trash"></i>
        </a>
    </td>
</tr>
{% endfor %} {% endblock %}

vencimientos/templates/vencimientos/venc_generate.html
{% extends 'list.html' %} {% load static %} 
{% block agregado %}

<div id="reportrange" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
    <i class="fa fa-calendar"></i>&nbsp;
    <span></span> <i class="fa fa-caret-down"></i>
</div>

{% endblock %} 
{% block columns %}
<tr>
    <th scope="col" style="width: 18%;">Período</th>
    <th scope="col" style="width: 25%;">Impuesto</th>
    <th scope="col" style="width: 27%;">Impuesto</th>
    <th scope="col" style="width: 10%;">Fecha</th>
    <th scope="col" style="width: 20%;">Opciones</th>
</tr>
{% endblock %} {% block rows %} {% endblock %}

{% block javascript %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script type="text/javascript">
    $(function() {
    
        var start = moment().subtract(29, 'days');
        var end = moment();
    
        function cb(start, end) {
            $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        }
    
        $('#reportrange').daterangepicker({
            startDate: start,
            endDate: end,
            ranges: {
               'Today': [moment(), moment()],
               'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
               'Last 7 Days': [moment().subtract(6, 'days'), moment()],
               'Last 30 Days': [moment().subtract(29, 'days'), moment()],
               'This Month': [moment().startOf('month'), moment().endOf('month')],
               'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
    
        cb(start, end);
    
    });
    </script>
{% endblock %}

vencimientos/templates/vencimientos/venc_imp_confirm_delete.html
{% extends 'base.html' %} {% block body %}
<h1>Borrar Vencimiento</h1>

<p>¿Estás seguro de borrar el vencimiento <b>{{ venc_imp }}</b>?</p>

<form action="" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-secondary btn-flat">
      <i class="fas fa-eraser"></i> Si! borrar.
  </button>
    <a href="{% url 'vencimientos:vi_list' %}" class="btn btn-danger btn-flat">
        <i class="fas fa-times"></i> Cancelar
    </a>
</form>
{% endblock %}

vencimientos/templates/vencimientos/venc_imp_form.html
{% extends 'form.html' %}

vencimientos/templates/vencimientos/venc_imp_list.html
{% extends 'list.html' %} {% load static %} {% block columns %}
<tr>
    <th scope="col" style="width: 15%;">Período</th>
    <th scope="col" style="width: 30%;">Impuesto</th>
    <th scope="col" style="width: 10%;">Cuit D</th>
    <th scope="col" style="width: 10%;">Cuit H</th>
    <th scope="col" style="width: 15%;">Fecha</th>
    <th scope="col" style="width: 20%;">Opciones</th>
</tr>
{% endblock %} {% block rows %} 
{% for obj in object_list %}
<tr>
    <td>{{ obj.periodo|date:'F Y' }}</td>
    <td>{{ obj.impuesto }}</td>
    <td>{{ obj.cuit_d }}</td>
    <td>{{ obj.cuit_h }}</td>
    <td>{{ obj.fecha|date:'d/m/Y' }}</td>
    <td class="text-center">
        <a href="{% url 'vencimientos:vi_update' obj.id %}" class="btn btn-warning btn-xs btn-flat">
            <i class="fas fa-edit"></i>
        </a>
        <a href="{% url 'vencimientos:vi_delete' obj.id %}" class="btn btn-danger btn-xs btn-flat">
            <i class="fas fa-trash"></i>
        </a>
    </td>
</tr>
{% endfor %} {% endblock %}